line-length = 88
target-version = "py313"
preview = true


[lint]
select = [
  "E",
  "W",
  "F",
  "I",
  "UP",
  "B",
  "SIM",
  "RUF",
  "C90",
  "PLC",
  "PLR",
  "PLW",
  "FBT",
  "ARG",
  "RET",
  "C4",
  "DTZ",
  "ISC",
  "PIE",
  "PTH",
  "PERF",
  "FURB",
  "LOG",
  "ANN",
  "A",
  "BLE",
  "TRY",
  "RSE",
  "TCH",
  "TID",
  "ERA",
  "COM",
  "S",
  "G",
  "N",
  "T20",
  "D",
  "RUF100",
]
ignore = ["D100", "D104", "D203", "D213"]


[lint.per-file-ignores]
"scripts/*" = ["D", "S603", "S607", "T20"]


[lint.mccabe]
max-complexity = 8


[lint.pylint]
max-args = 5
max-returns = 8
max-branches = 10
max-statements = 30


[lint.pydocstyle]
convention = "google"


[lint.flake8-type-checking]
strict = true


[lint.flake8-annotations]
suppress-dummy-args = true
allow-star-arg-any = true
mypy-init-return = true


[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = true
