extends: default
rules:
  line-length:
    max: 120
    level: warning
  document-start:
    present: false
  truthy:
    allowed-values: ["true", "false", "on", "off"]
ignore: |
  .direnv/
  .pre-commit-config.yaml
  .github/labeler.yml
  result/
  config/home-manager/result/
