[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = [
    # Default rules
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # pyflakes
    "UP",     # pyupgrade
    "B",      # flake8-bugbear
    "SIM",    # flake8-simplify
    "I",      # isort
    
    # Functional programming related
    "RUF",    # Ruff-specific rules
    "C90",    # mccabe complexity
    "PLC",    # Pylint conventions
    "PLR",    # Pylint refactor
    "PLW",    # Pylint warnings
    "FBT",    # flake8-boolean-trap (avoid boolean parameters)
    "ARG",    # flake8-unused-arguments
    "RET",    # flake8-return
    "C4",     # flake8-comprehensions
    "DTZ",    # flake8-datetimez (timezone aware datetime)
    "ISC",    # flake8-implicit-str-concat
    "PIE",    # flake8-pie
    "PT",     # flake8-pytest-style
    "PTH",    # flake8-use-pathlib
    "PERF",   # perflint
    "FURB",   # refurb (modern Python patterns)
    "LOG",    # flake8-logging
    "RUF100", # Unused noqa
    
    # Documentation
    "D",      # pydocstyle
]

ignore = [
    "D100",   # Missing docstring in public module
    "D104",   # Missing docstring in public package
    "D203",   # 1 blank line required before class docstring
    "D213",   # Multi-line docstring summary should start at the second line
]

[tool.ruff.lint.per-file-ignores]
"scripts/*" = ["D"]  # Don't require docstrings in scripts

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pylint]
max-args = 5
max-returns = 3
max-branches = 10
max-statements = 30

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false